version: '3.8'

services:
  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production

  user-service:
    build:
      context: ./services/user-service
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production

  web-client:
    build:
      context: ./web-client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - auth-service
      - user-service

networks:
  default:
    driver: bridge